# [START appengine_websockets_yaml]
runtime: nodejs
env: flex

# going to need to stick to a single instance unless we build in load balancing to keep players in the same game on the same instance
manual_scaling:
  instances: 1

network:
  session_affinity: true
# [END appengine_websockets_yaml]